// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1s2T5CMrQ6FGrQ0W4Zrxy0Js2QOLbKKg',
    appId: '1:698611507052:web:c7edb6b024c78708b29d49',
    messagingSenderId: '698611507052',
    projectId: 'saudi-tourism-app',
    authDomain: 'saudi-tourism-app.firebaseapp.com',
    storageBucket: 'saudi-tourism-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALtAslY3OzJkpFL4LxdGQNvpkHz3OZvr8',
    appId: '1:698611507052:android:4e33e4d34633b09bb29d49',
    messagingSenderId: '698611507052',
    projectId: 'saudi-tourism-app',
    storageBucket: 'saudi-tourism-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYMEFEdMOolMrRRkeHXzw3Fh_wecNid9c',
    appId: '1:698611507052:ios:baa64e01b8992476b29d49',
    messagingSenderId: '698611507052',
    projectId: 'saudi-tourism-app',
    storageBucket: 'saudi-tourism-app.firebasestorage.app',
    iosBundleId: 'com.example.tourismapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYMEFEdMOolMrRRkeHXzw3Fh_wecNid9c',
    appId: '1:698611507052:ios:baa64e01b8992476b29d49',
    messagingSenderId: '698611507052',
    projectId: 'saudi-tourism-app',
    storageBucket: 'saudi-tourism-app.firebasestorage.app',
    iosBundleId: 'com.example.tourismapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1s2T5CMrQ6FGrQ0W4Zrxy0Js2QOLbKKg',
    appId: '1:698611507052:web:5113262bf8c67053b29d49',
    messagingSenderId: '698611507052',
    projectId: 'saudi-tourism-app',
    authDomain: 'saudi-tourism-app.firebaseapp.com',
    storageBucket: 'saudi-tourism-app.firebasestorage.app',
  );
}
